name: reactive.js CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: self-hosted

    steps: 
      # - name: Fix permissions
      #   run: sudo chmod -R u+rwx /var/www/reactive/_work/reactive-solutions/reactive-solutions

      # - name: Force clean repository
      #   run: |
      #     sudo rm -rf /var/www/reactive/_work/reactive-solutions/reactive-solutions/* || true
      # - name: Fix permissions for reactive-solutions
      #   run: |
      #     sudo chmod -R u+rwx /var/www/reactive/_work/reactive-solutions/reactive-solutions || true
      #     sudo chown -R $(whoami):$(whoami) /var/www/reactive/_work/reactive-solutions/reactive-solutions || true

      # - name: Clean reactive-solutions git directory
      #   run: sudo rm -rf /var/www/reactive/_work/reactive-solutions/reactive-solutions/.git || true

      # - name: Debug directory permissions
      #   run: ls -ld /var/www/reactive/_work/reactive-solutions/reactive-solutions

      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          set-safe-directory: true

      - name: Create .env file
        run: |
          echo "REACT_APP_SERVICE_ID=service_6yot61z" >> .env
          echo "REACT_APP_TEMPLATE_ID=template_ipodwef" >> .env
          echo "REACT_APP_USER_ID=user_SQuNzUKyVdTacaDdvFSWD" >> .env

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies 
        run: 
          npm install --legacy-peer-deps

      - name: Audit fix 
        run: 
          npm audit fix --legacy-peer-deps

      - name: Build 
        run: 
          npm run build
      
